### ISSUE TITLE
Chinese menu can't display properly

### ISSUE THREAD

**Issue by Badbrain2077** [EwenQuim/renpy-graphviz#23]
BEFORE FILING THIS:
- [x] My game is made with the Ren'Py visual novel game engine
- [ ] My game is uploaded on GitHub
- [ ] I have tried the [online tool](https://renpy.amethysts.studio) by entering `myusername/mygame` and it works
---
Hello, 

I make Renpy games in Chinese.

Label_name use Chinese won't be able to run.

Label_name use English can run, but the Chinese menu can't display properly.(I guess Japanese has the same problem.)

![image](https://user-images.githubusercontent.com/59142252/173231550-af09f08d-3872-47cc-b625-2e5e9fd96995.png)

Thanks.

**Comment by EwenQuim** [comment]
Hi, can I have an example of what a Ren'Py script can look in Chinese ? 

It'll help me fix this issue :) Thanks in advance

**Comment by EwenQuim** [comment]
Hello @Badbrain2077 !
The parser currently support understanding Chinese characters.  This means the Chinese labels won't be lost 🎉

Unfortunately, my program relies on a library that cannot display them. So when you use the program, you can open the `renpy-graphviz.dot` file with a text editor, and paste the content to a website like <https://dreampuf.github.io/GraphvizOnline>

<img width="497" alt="image" src="https://user-images.githubusercontent.com/46993939/173518313-4e894ace-7120-499c-b1c2-fcba3dab2e5e.png">

⬇️ Notice that the labels are indeed in Chinese ! The parser understands them now
<img width="792" alt="image" src="https://user-images.githubusercontent.com/46993939/173518537-53428dc1-e92e-4ef9-928c-900960279db8.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/46993939/173518424-4f0762e6-812a-4e27-b575-830f77db9c2d.png">

I will probably raise an issue on <https://github.com/goccy/go-graphviz> to integrate the drawing of Chinese characters right in the program.

---

I hope this will help you
! Don't hesitate to support the project by sharing the Github page around you and star ⭐️ the repo!

**Comment by Badbrain2077** [comment]
Thank you very much for your support.:)

I hope the great project is getting better and better❤️!

I have already star⭐️ !
