### ISSUE TITLE
Could the browser version support HTTPS public repos?

### ISSUE THREAD

**Issue by Daxode** [EwenQuim/renpy-graphviz#53]
Assuming the browser version is still client based. It would be nice if it could work without the API key, like normal git when only reading. Just passing in the public git HTTPS link. That way stuff like gitlab, bitbucket etc. could work too, without needing an API key per platform!

**Comment by EwenQuim** [comment]
I don't think so, it would require the client to download files and I don't know if it's possible client side. That would have been awesome indeed.

I would be happy if this tool supports Gitlab, BitBucket, Gitea... so don't hesitate to make a PR if you have some time!

We can also add individual support for each platform.
