### ISSUE TITLE
Underscores in labelnames not showing in image

### ISSUE THREAD

**Issue by FaceCrap** [EwenQuim/renpy-graphviz#54]
Haven't found a mention of this, but I noticed that underscores in label names don't get drawn on the outputted image.

If you're not familiar with the renpy code, it'll take some guessing attempts to find the correct label.

**Comment by EwenQuim** [comment]
This is done on purpose to make the graph prettier.

I don't know if we should disable it or not, what do you think? You're the first to tell me this

**Comment by FaceCrap** [comment]
That actually surprised me. Would have expected to find a mention, but nothing. 

I didn't know this tool existed, only stumbled on it by accident, because a game dev left a copy in the distribution archive.

Which is why I haven't used it that much and only now stumble over this 'feature'.
Most games I tried it on so far didn't use underscores in labels, but the last one does use them a lot. 
I found it makes it hard to find the label in the code if it's left out. 

If you're concerned about how it looks, maybe add it as an option to allow them via commandline or config file?

**Comment by EwenQuim** [comment]
I do not plan on working on this, but happy to accept a PR if you contribute ! That's just an option to add and code to remove, that can be done easily I think. If you're not familiar with Go, don't be afraid, it isn't complicated to use if you know python.

Thanks again!

**Comment by FaceCrap** [comment]
> I do not plan on working on this, but happy to accept a PR if you contribute ! 
> That's just an option to add and code to remove, that can be done easily I think. 
> If you're not familiar with Go, don't be afraid, it isn't complicated to use if you know python.

I've got zero Go experience, and learning howto is not an option just to add a commandline option for this to ignore 1 line... 
(at least I think it's just the one line) 
Think I found which line to remove in graph.go... if I'm right all that would be needed is to remove this call ```labelName := beautifyLabel(label, tags)``` from line 97
Now to get this thing compiled. HOW? 

There's absolutely zero information here on how to build an exe from a local repo copy...
Would you be so kind and explain how I can generate an executable from the source?

**Comment by EwenQuim** [comment]
> Contrary to what I found after doing a web search, just doing go build in the root folder of the repo did not generate an executable in the same folder...

It should have, that's weird...

**Comment by FaceCrap** [comment]
no such luck, this is the output but no exe file. 

```
E:\Programs64\Dev\Go\bin\GraphViz>..\go build -o my-renpy-graphviz-executable > gobuild.log
go: downloading github.com/skratchdot/open-golang v0.0.0-20200116055534-eef842397966
go: downloading github.com/fatih/color v1.16.0
go: downloading github.com/goccy/go-graphviz v0.1.2
go: downloading github.com/emicklei/dot v1.6.2
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading golang.org/x/sys v0.18.0
go: downloading golang.org/x/image v0.14.0
go: downloading github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0
go: downloading github.com/fogleman/gg v1.3.0
go: downloading github.com/pkg/errors v0.9.1
package pkg.amethysts.studio/renpy-graphviz
        imports github.com/goccy/go-graphviz
        imports github.com/goccy/go-graphviz/cgraph
        imports github.com/goccy/go-graphviz/internal/ccall: build constraints exclude all Go files in C:\Users\FaceCrap\go\pkg\mod\github.com\goccy\go-graphviz@v0.1.2\internal\ccall
```

go install just repeated the last bit and still no exe anywhere on my system.
```
package pkg.amethysts.studio/renpy-graphviz
        imports github.com/goccy/go-graphviz
        imports github.com/goccy/go-graphviz/cgraph
        imports github.com/goccy/go-graphviz/internal/ccall: build constraints exclude all Go files in C:\Users\FaceCrap\go\pkg\mod\github.com\goccy\go-graphviz@v0.1.2\internal\ccall
```

**Comment by EwenQuim** [comment]
Ah yes indeed, it might be because of C build constraints on windows from `github.com/goccy/go-graphviz`, a third party library `renpy-graphviz` uses to draw the PNG graph.

<img width="660" alt="image" src="https://github.com/EwenQuim/renpy-graphviz/assets/46993939/2076aa81-7b0d-4b7d-ae8d-925dea134d0b">

I think you can reopen [this issue](https://github.com/goccy/go-graphviz/issues/27). Thanks for the details !

**Comment by FaceCrap** [comment]
So we're now almost two months later and I'm still facing this issue...

Since it's not gonna look like it's getting resolved, I'm stuck, since you refuse to have labels displayed as they are but decide to replace characters making up a labelname (which in itself already is weird if you want to debug a project since you have no way to match the output to your project) and I can't build it due to this stupid issue, I'm hosed...

**Comment by EwenQuim** [comment]
I'm so sorry, that's a shame that https://github.com/goccy/go-graphviz/issues/86 does not work on Windows, it really sucks

**Comment by FaceCrap** [comment]
sigh... tried the suggestion made in  [goccy/go-graphviz#86](https://github.com/goccy/go-graphviz/issues/86) (setting CGO_ENABLED=1)

This time it suddenly started looking for gcc... ???

Ok, so downloaded mingw64, added it to the path and of course, a whole slew of new errors...

[output.txt](https://github.com/user-attachments/files/16603824/output.txt)

care to tell me what I can do here (and please keep in mind I know nothing about GO, and even less about compiling with gcc.)
