### ISSUE TITLE
Segfault on BOM

### ISSUE THREAD

**Issue by alk0** [EwenQuim/renpy-graphviz#8]
The tool crashes if the .rpy file has a UTF-8 [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) marker (EF BB BF) at the start. Test file attached:
[test_bom.rpy.txt](https://github.com/EwenQuim/renpy-graphviz/files/6490032/test_bom.rpy.txt)

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x509c16]
> 
> goroutine 1 [running]:
> pkg.amethysts.studio/renpy-graphviz/parser.(*RenpyGraph).AddEdge(0xc0000cdd80, 0x0, 0x0, 0xc0000cdde0, 0x3, 0x3)
>         /source/parser/graph.go:115 +0x136
> pkg.amethysts.studio/renpy-graphviz/parser.Graph(0xc0000d6100, 0x3, 0x4, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /source/parser/parser.go:48 +0x50f
> main.main()
>         /source/main.go:17 +0xa5

**Comment by EwenQuim** [comment]
Several options for you:
- do not use BOM markers, simply use utf-8 standard format
- do not place a label on the first line -just a comment or literally will be ok:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/46993939/118478754-898cd500-b710-11eb-8b7c-0d30b4588e97.png">

Hope this helps.
Thank you for using this tool :)

**Comment by alk0** [comment]
Sure I know how to get rid of it manually, and I never use BOM myself, but others do. The idea is to use the tool to analyze _someone else's_ VN with ~20 Mb of interconnected .rpy sources in ~200 files, with some of them having this pesky marker. _(Renpy-graphviz is of little use anyway for this particular project (it has complex flag-driven logic), but this is another story.)_ And yes, I know that Go is intentionally reluctant to handle BOMs, since they are not a part of what they consider a standard. Anyway, if one day you decide to implement skipping the BOM, here are some ideas:
https://stackoverflow.com/questions/21371673/reading-files-with-a-bom-in-go
https://github.com/dimchansky/utfbom
https://github.com/spkg/bom

> Thank you for using this tool :)

Thank **you** for making it :) It's still the best of what there is, and I'm sure there's room for improvement.

**Comment by alk0** [comment]
Oh, and I forgot to mention the most important part - the problem was not just the inability of renpy-graphviz to handle the BOM in itself, but the fact that the tool just crashed with no explanation, and I had to investigate the cause, having no idea _why_ it did, given a perfectly valid (from any reasonable point of view) input (for me it was not obvious at all, and took quite a while to figure it out; dunno, maybe I'm dumb).

**Comment by alk0** [comment]
The recipe from StackOverflow seems to do the trick, BOM-poisoned files seem to be handled OK now (maybe needs a couple additional checks, in case the file is less than 3 bytes long).

```
diff --git a/parser/filehandling.go b/parser/filehandling.go
index dabbeb7..b8debd5 100644
--- a/parser/filehandling.go
+++ b/parser/filehandling.go
@@ -2,6 +2,7 @@ package parser
 
 import (
 	"bufio"
+	"io"
 	"log"
 	"os"
 	"path/filepath"
@@ -25,6 +26,18 @@ func GetRenpyContent(rootPath string) []string {
 				log.Fatalf("failed to open file: %s", err)
 			}
 
+            var bom [3]byte
+            _, err = io.ReadFull(readFile, bom[:])
+            if err != nil {
+                log.Fatal(err)
+            }
+            if bom[0] != 0xef || bom[1] != 0xbb || bom[2] != 0xbf {
+                _, err = readFile.Seek(0, 0) // Not a BOM -- seek back to the beginning
+                if err != nil {
+                    log.Fatal(err)
+                }
+            }
+
 			fileScanner := bufio.NewScanner(readFile)
 			fileScanner.Split(bufio.ScanLines)
 
```

**Comment by EwenQuim** [comment]
I'll merge this tomorrow, thanks for the proposal ! :)

Don't hesitate to create a PR yourself and add a test if you have time ! I'll do it myself otherwise.

**Comment by alk0** [comment]
Oh, it's not about time, I'm afraid my git-fu is just not good enough for this, I've no idea how to create PRs here. Furthermore, my Go-fu level is about zero, too.
